version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SprintPlanningPoker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-acxootqiq4w0"
s3_prefix = "SprintPlanningPoker"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"planningpoker_connections\""
