import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const icons = [
  ['light', 'rotate-left'],
  ['light', 'snooze'],
  ['light', 'moon'],
  ['light', 'eye'],
  ['light', 'microchip-ai'],
  ['light', 'user'],
  ['light', 'brain'],
  ['light', 'sun-bright'],
  ['solid', 'spade'],
  ['solid', 'heart'],
  ['solid', 'diamond'],
  ['solid', 'club'],
] as const;

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const fontAwesomeDir = join(root, 'node_modules/@fortawesome/fontawesome-pro');
const outputDir = join(root, 'src/components/icons');

const pascalCase = (name: string) =>
  name.replace(/(^|-)([a-z])/g, (_, _separator: string, letter: string) => letter.toUpperCase());

try {
  await stat(fontAwesomeDir);
} catch {
  throw new Error(
    '@fortawesome/fontawesome-pro is missing. Run `bun run icons:install` first.',
  );
}

await mkdir(outputDir, { recursive: true });

const exports: string[] = [];

for (const [style, name] of icons) {
  const sourcePath = join(fontAwesomeDir, 'svgs', style, `${name}.svg`);
  const source = await readFile(sourcePath, 'utf8');
  const viewBox = source.match(/\bviewBox=["']([^"']+)["']/)?.[1];
  const paths = [...source.matchAll(/<path\b[^>]*\bd=["']([^"']+)["'][^>]*\/?\s*>/g)].map(
    (match) => match[1],
  );

  if (!viewBox || paths.length === 0) {
    throw new Error(`Could not parse ${sourcePath}`);
  }

  const componentName = pascalCase(name);
  const pathElements = paths.map((path) => `    <path d="${path}" />`).join('\n');
  const component = `// Generated by scripts/generate-icons.ts. Do not hand-edit.\nimport type { SVGProps } from 'react';\n\nexport const ${componentName} = (props: SVGProps<SVGSVGElement>) => (\n  <svg\n    viewBox="${viewBox}"\n    width="1em"\n    height="1em"\n    fill="currentColor"\n    display="inline-block"\n    aria-hidden="true"\n    focusable="false"\n    {...props}\n  >\n${pathElements}\n  </svg>\n);\n`;

  await writeFile(join(outputDir, `${name}.tsx`), component);
  exports.push(`export { ${componentName} } from './${name}';`);
}

await writeFile(
  join(outputDir, 'index.ts'),
  `// Generated by scripts/generate-icons.ts. Do not hand-edit.\n${exports.join('\n')}\n`,
);
