// Generated by scripts/generate-icons.ts. Do not hand-edit.
import type { SVGProps } from 'react';

export const Diamond = (props: SVGProps<SVGSVGElement>) => (
  <svg
    viewBox="0 0 512 512"
    width="1em"
    height="1em"
    fill="currentColor"
    display="inline-block"
    aria-hidden="true"
    focusable="false"
    {...props}
  >
    <path d="M284.3 11.7c-15.6-15.6-40.9-15.6-56.6 0l-216 216c-15.6 15.6-15.6 40.9 0 56.6l216 216c15.6 15.6 40.9 15.6 56.6 0l216-216c15.6-15.6 15.6-40.9 0-56.6l-216-216z" />
  </svg>
);
